version: '3'

services:
  postgres:
    image: postgres:11-alpine3.17
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456
    volumes:
      - ./.docker/data-postgres:/var/lib/postgresql/data
      - ./.docker/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5440:5432